# Generated by Django 4.1.5 on 2023-01-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('e_date', models.DateField()),
                ('e_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('info', models.TextField(max_length=1000)),
            ],
        ),
    ]
