# Generated by Django 4.1.5 on 2023-01-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
