# Generated by Django 4.1.5 on 2023-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_userphoto_userphotos_meetsuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphotos',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='meetsuser',
            name='photo',
        ),
        migrations.AlterField(
            model_name='userphotos',
            name='photo',
            field=models.ImageField(upload_to='photos/users/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='meetsuser',
            name='photo',
            field=models.ManyToManyField(blank=True, to='users.userphotos'),
        ),
    ]
