# Generated by Django 4.1.5 on 2023-02-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_meetsuser_photo_meetsuser_user_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetsuser',
            old_name='user_photo',
            new_name='photo',
        ),
    ]
