# Generated by Django 4.1.5 on 2023-01-22 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='e_meets',
        ),
        migrations.AddField(
            model_name='meet',
            name='meet_event',
            field=models.ManyToManyField(blank=True, to='meets.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='willing_people',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meet',
            name='people',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meet',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
