# Generated by Django 4.1.5 on 2023-01-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_remove_event_e_meets_meet_meet_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'ивент', 'verbose_name_plural': 'ивенты'},
        ),
        migrations.AlterModelOptions(
            name='meet',
            options={'verbose_name': 'встреча', 'verbose_name_plural': 'встречи'},
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='meet',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='meet',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
