# Generated by Django 4.1.5 on 2023-01-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_appphoto_event_photo_meet_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='photo',
        ),
        migrations.AddField(
            model_name='event',
            name='e_photo',
            field=models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='meet',
            name='m_photo',
            field=models.ImageField(blank=True, upload_to='photos/meets/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='AppPhoto',
        ),
    ]
