# Generated by Django 4.1.5 on 2023-02-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(2, 'Доступ по ссылке'), (0, 'Приватное мероприятие'), (1, 'Открытое мероприятие')], default=0, max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[(2, 'Доступ по ссылке'), (0, 'Приватная встреча'), (1, 'Открытая встреча')], default=0, max_length=30, verbose_name='Статус'),
        ),
    ]
