# Generated by Django 4.1.5 on 2023-02-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0009_event_created_at_event_owner_meet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(0, 'Приватное мероприятие'), (2, 'Доступ по ссылке'), (1, 'Открытое мероприятие')], default=0, max_length=30, verbose_name='Статус'),
        ),
    ]
