# Generated by Django 4.1.5 on 2023-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0013_alter_event_status_alter_meet_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(0, 'Приватное мероприятие'), (1, 'Открытое мероприятие'), (2, 'Доступ по ссылке')], default=0, max_length=30, verbose_name='Статус'),
        ),
    ]
