# Generated by Django 4.1.5 on 2023-02-11 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meets', '0014_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='user_meets', to=settings.AUTH_USER_MODEL, verbose_name='Участники встречи'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(0, 'Приватное мероприятие'), (2, 'Доступ по ссылке'), (1, 'Открытое мероприятие')], default=0, max_length=30, verbose_name='Статус'),
        ),
        migrations.RemoveField(
            model_name='meet',
            name='meet_event',
        ),
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[(1, 'Открытая встреча'), (2, 'Доступ по ссылке'), (0, 'Приватная встреча')], default=0, max_length=30, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='meet',
            name='meet_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_linked_meets', to='meets.event', verbose_name='Связанное мероприятие'),
        ),
    ]
