# Generated by Django 4.1.5 on 2023-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0015_meet_people_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(1, 'Открытое мероприятие'), (2, 'Доступ по ссылке'), (0, 'Приватное мероприятие')], default=0, max_length=30, verbose_name='Статус'),
        ),
    ]
