# Generated by Django 4.1.5 on 2023-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0019_alter_event_status_alter_meet_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Приватное мероприятие'), (2, 'Доступ по ссылке'), (1, 'Открытое мероприятие')], default=0, max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.IntegerField(choices=[(0, 'Приватная встреча'), (1, 'Открытая встреча'), (2, 'Доступ по ссылке')], default=0, max_length=30, verbose_name='Статус'),
        ),
    ]
